version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-ef
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: elasticsearch-ef
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  eventstore:
    image: eventstore/eventstore
    container_name: eventstore-ef
    ports:
      - "1113:1113"
      - "2113:2113"
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver-ef
    environment:
      - SA_PASSWORD=Password12!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"